# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pcor <- function(x) {
    .Call('_ConAn_pcor', PACKAGE = 'ConAn', x)
}

erase_mods <- function(x, ix) {
    .Call('_ConAn_erase_mods', PACKAGE = 'ConAn', x, ix)
}

atanh_lower_tri <- function(x) {
    .Call('_ConAn_atanh_lower_tri', PACKAGE = 'ConAn', x)
}

atanh_lower_tri_pcor <- function(x) {
    .Call('_ConAn_atanh_lower_tri_pcor', PACKAGE = 'ConAn', x)
}

atanh_lower_tri_erase_mods_pcor <- function(x, ix) {
    .Call('_ConAn_atanh_lower_tri_erase_mods_pcor', PACKAGE = 'ConAn', x, ix)
}

mean_atanh_lower_tri_erase_mods_pcor <- function(x, ix) {
    .Call('_ConAn_mean_atanh_lower_tri_erase_mods_pcor', PACKAGE = 'ConAn', x, ix)
}

bg_corrected_atanh_lower_tri_pcor <- function(x, bg) {
    .Call('_ConAn_bg_corrected_atanh_lower_tri_pcor', PACKAGE = 'ConAn', x, bg)
}

mean_bg_corrected_atanh_lower_tri_pcor <- function(x, bg) {
    .Call('_ConAn_mean_bg_corrected_atanh_lower_tri_pcor', PACKAGE = 'ConAn', x, bg)
}

modular_differential_connectivity <- function(xr, xt, bgr, bgt, type) {
    .Call('_ConAn_modular_differential_connectivity', PACKAGE = 'ConAn', xr, xt, bgr, bgt, type)
}

